### ISSUE TITLE
ImportError: cannot import name sensor

### ISSUE THREAD

**Issue by Malathi15** [carla-simulator/carla#3215]
Hi, 
My System specifications:
OS: Ubuntu 18.04,
Memory: 15.7 GiB,
Processor: AMD® Ryzen 7 3800x 8-core processor × 16,
GPU 4 GiB.
I have downloaded the CARLA Simulator. While executing the python script I got an `ImportError: cannot import name sensor`
```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "module_7.py", line 33, in <module>
    from carla            import sensor
ImportError: cannot import name 'sensor'
```
I have tried with python 3.6 and python 2.7. I got the same error in the both version (Please check the screenshot)
![python3 6](https://user-images.githubusercontent.com/46995564/90954605-2fb5f200-e493-11ea-9299-78ece60ca672.png)
![python2 7](https://user-images.githubusercontent.com/46995564/90954611-3d6b7780-e493-11ea-9769-8190446e9487.png)

Please help me to solve this

Thanks in Advance
Malathi K

**Comment by germanros1987** [comment]
@Malathi15 that has nothing to do with CARLA. That is not our code, so please check out with the people who made that code.

**Comment by AD1D1** [comment]
> Hi,
> My System specifications:
> OS: Ubuntu 18.04,
> Memory: 15.7 GiB,
> Processor: AMD® Ryzen 7 3800x 8-core processor × 16,
> GPU 4 GiB.
> I have downloaded the CARLA Simulator. While executing the python script I got an `ImportError: cannot import name sensor`
> 
> ```
> pygame 1.9.6
> Hello from the pygame community. https://www.pygame.org/contribute.html
> Traceback (most recent call last):
>   File "module_7.py", line 33, in <module>
>     from carla            import sensor
> ImportError: cannot import name 'sensor'
> ```
> 
> I have tried with python 3.6 and python 2.7. I got the same error in the both version (Please check the screenshot)
> ![python3 6](https://user-images.githubusercontent.com/46995564/90954605-2fb5f200-e493-11ea-9299-78ece60ca672.png)
> ![python2 7](https://user-images.githubusercontent.com/46995564/90954611-3d6b7780-e493-11ea-9769-8190446e9487.png)
> 
> Please help me to solve this
> 
> Thanks in Advance
> Malathi K

Hey I have the same issue please help

**Comment by Aravindseenu** [comment]
@Malathi15 @AD1D1 The reason for your guys not able to import the module is due to access restriction. simple solution to overcome this is run your code as super user ,type sudo python3 and execute your required code. It should work fine.

**Comment by Aravindseenu** [comment]
> Hi,
> My System specifications:
> OS: Ubuntu 18.04,
> Memory: 15.7 GiB,
> Processor: AMD® Ryzen 7 3800x 8-core processor × 16,
> GPU 4 GiB.
> I have downloaded the CARLA Simulator. While executing the python script I got an `ImportError: cannot import name sensor`
> 
> ```
> pygame 1.9.6
> Hello from the pygame community. https://www.pygame.org/contribute.html
> Traceback (most recent call last):
>   File "module_7.py", line 33, in <module>
>     from carla            import sensor
> ImportError: cannot import name 'sensor'
> ```
> 
> I have tried with python 3.6 and python 2.7. I got the same error in the both version (Please check the screenshot)
> ![python3 6](https://user-images.githubusercontent.com/46995564/90954605-2fb5f200-e493-11ea-9299-78ece60ca672.png)
> ![python2 7](https://user-images.githubusercontent.com/46995564/90954611-3d6b7780-e493-11ea-9769-8190446e9487.png)
> 
> Please help me to solve this
> 
> Thanks in Advance
> Malathi K

your problem is fixed just execute your code as super user
sudo python3 module_7.py will fix the issue.

**Comment by KuldeepDileep** [comment]
> > Hi,
> > My System specifications:
> > OS: Ubuntu 18.04,
> > Memory: 15.7 GiB,
> > Processor: AMD® Ryzen 7 3800x 8-core processor × 16,
> > GPU 4 GiB.
> > I have downloaded the CARLA Simulator. While executing the python script I got an `ImportError: cannot import name sensor`
> > ```
> > pygame 1.9.6
> > Hello from the pygame community. https://www.pygame.org/contribute.html
> > Traceback (most recent call last):
> >   File "module_7.py", line 33, in <module>
> >     from carla            import sensor
> > ImportError: cannot import name 'sensor'
> > ```
> > 
> > 
> > I have tried with python 3.6 and python 2.7. I got the same error in the both version (Please check the screenshot)
> > ![python3 6](https://user-images.githubusercontent.com/46995564/90954605-2fb5f200-e493-11ea-9299-78ece60ca672.png)
> > ![python2 7](https://user-images.githubusercontent.com/46995564/90954611-3d6b7780-e493-11ea-9769-8190446e9487.png)
> > Please help me to solve this
> > Thanks in Advance
> > Malathi K
> 
> your problem is fixed just execute your code as super user
> sudo python3 module_7.py will fix the issue.

@Aravindseenu didnt work for me. I am still getting the following error: 
ImportError: cannot import name 'sensor' from 'carla' (/home/kuldeep/Downloads/CARLA_0.9.10/PythonAPI/carla/dist/carla-0.9.10-py3.7-linux-x86_64/carla/__init__.py)

**Comment by Aravindseenu** [comment]
from your terminal I can see the default path of the project are changed.(course1finalproject) which should be in the path.

in you case your are calling a module sensor from carla which is not in the required directory. I think this should be the problem. 

try downloading latest version and make sure python version is 3.7.4 if python3 is used. if every thing is configured properly then you should be able to follow the instruction as stated in following links 

windows : https://youtu.be/_vklQaG2bss

ubuntu : https://youtu.be/cfvG_qQOCIE 

hope these will help you.

**Comment by KuldeepDileep** [comment]
> 
> 
> from your terminal I can see the default path of the project are changed.(course1finalproject) which should be in the path.
> 
> in you case your are calling a module sensor from carla which is not in the required directory. I think this should be the problem.
> 
> try downloading latest version and make sure python version is 3.7.4 if python3 is used. if every thing is configured properly then you should be able to follow the instruction as stated in following links
> 
> windows : https://youtu.be/_vklQaG2bss
> 
> ubuntu : https://youtu.be/cfvG_qQOCIE
> 
> hope these will help you.

@Aravindseenu Thankyou so much for your prompt response. Actually, the built-in examples of CARLA work for me. I am trying to run module_7.py file from [https://github.com/paulyehtw/Motion-Planning-on-CARLA](url). I have unzipped the content of [https://github.com/paulyehtw/Motion-Planning-on-CARLA](this) repository in /home/kuldeep/Downloads/CARLA_0.9.10/PythonAPI though it says to put the folder in PythonClient but I don't have that folder in my CARLA_0.9.10 so I have cloned it in PythonAPI folder. When I execute module_7.py file from there I get this error:
ImportError: cannot import name 'sensor' from 'carla' (/home/kuldeep/Downloads/CARLA_0.9.10/PythonAPI/carla/dist/carla-0.9.10-py3.7-linux-x86_64/carla/init.py)

Would appreciate any help!

**Comment by Aravindseenu** [comment]
Hello @KuldeepDileep 
Your problem is caused due to the misplacing of the python scripts. 
when you try to import module from a script it has to be in proper folder for python to import the module. 

if your are able to run the examples , edit the script as per the examples (check how the running examples calls the sensor)

I can understand the problem now.. the error is should be queried at https://github.com/paulyehtw/Motion-Planning-on-CARLA/issues 

as @germanros1987 said the issue is not due to CARLA..  this is forum to open issues in scripts provided by the CARLA. 

the python script which you are trying to run is for specified version of CARLA where the example runs perfectly.
