### ISSUE TITLE
Ros-Bridge on Ubuntu 20.04

### ISSUE THREAD

**Issue by MrLerry** [carla-simulator/carla#5460]
Hi guys,

i want to retrieve rosbags of the lidar sensor, so I installes Ros-noetic and followed the docs to build the carla-ros-bridge source repository.
I got everything set up without getting an error message but when executing `roslaunch carla_ros_bridge carla_ros_bridge.launch` ros crashes and i get this Error: 
```
File "/home/Lerry/CARLA/carla/PythonAPI/carla/dist/carla-0.9.13-py3.8-linux-x86_64.egg/carla/libcarla.py", line 6, in __bootstrap__
ImportError: /home/Lerry/.cache/Python-Eggs/carla-0.9.13-py3.8-linux-x86_64.egg-tmp/carla/libcarla.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Py_tracemalloc_config
================================================================================REQUIRED process [carla_ros_bridge-2] has died!
process has died [pid 17962, exit code 1, cm**d /home/Lerry/CARLA/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py __name:=carla_ros_bridge __log:=/home/Lerry/.ros/log/7fc0e68e-da6d-11ec-92fe-83ab85a3c95b/carla_ros_bridge-2.log].
log file: /home/Lerry/.ros/log/7fc0e68e-da6d-11ec-92fe-83ab85a3c95b/carla_ros_bridge-2*.log
Initiating shutdown!
================================================================================
[carla_ros_bridge-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
```
Cant find anything related to the undefined symbol: _Py_tracemalloc_config so im a bit stuck here.
Any advice?

Cheers
Lerry

**Comment by fangchaooo** [comment]
your lib (libboost) version is not  correct. you can ldd the libcarla，find correct link or unlink symbol

**Comment by Felix-FN** [comment]
Yes thank you. Figured it out and forgot to close this issue.
Thanks anyway :)

**Comment by MrLerry** [comment]
Yes i figured it out eventually.  Just forgot to close this issue ^^
Thanks anyway.

**Comment by avpodtikhov** [comment]
Faced the same issue. Could you please tell how did you manage to solve it?

**Comment by Ahmed-Radwan094** [comment]
@MrLerry Can you share how did solve the issue as I am currently facing it?

**Comment by MrLerry** [comment]
> @MrLerry Can you share how did solve the issue as I am currently facing it?

Hi @Ahmed-Radwan094 , it was the python version if i remember correctly. Use python2 for ROS and it should work.

**Comment by Ahmed-Radwan094** [comment]
@MrLerry I am using ROS noetic which is python 3 based, so I think maybe the problem source is not the same.

**Comment by Ahmed-Radwan094** [comment]
I fixed it. The default python used by ubuntu was python 2.7 and I changed it to be python 3.8

**Comment by hexrefugee** [comment]
> 

hi, I met the same problem. And I follow your advice changed python 3.8

v2t-smi@v2tsmi-MS-7D89:~/carla-ros-bridge/catkin_ws$ python3 -V
Python 3.8.10

but this error didn't solve. Can you give me some advices?

**Comment by hexrefugee** [comment]
> I fixed it. The default python used by ubuntu was python 2.7 and I changed it to be python 3.8

hi, I met the same problem. And I follow your advice changed python 3.8

v2t-smi@v2tsmi-MS-7D89:~/carla-ros-bridge/catkin_ws$ python3 -V
Python 3.8.10

but this error didn't solve. Can you give me some advices?

**Comment by Ahmed-Radwan094** [comment]
The problem for me was the mismatch between the python version used to build carla and the one used by the system. Maybe you built carla with another version than 3.8.10. I am not expert in the matter but this was my case.

**Comment by hexrefugee** [comment]
> @hexrefugee The problem for me was the mismatch between the python version used to build carla and the one used by the system. Maybe you built carla with another version than 3.8.10. I am not expert in the matter, but this was my case.

thank for your reply. I remember in the first time I build carla use default python, maybe the system default python version is 2, I 'll try to rebuild carla in python 3. Appreciated.

**Comment by hexrefugee** [comment]
> @hexrefugee The problem for me was the mismatch between the python version used to build carla and the one used by the system. Maybe you built carla with another version than 3.8.10. I am not expert in the matter, but this was my case.

sadly, I failed. I just rebuild carla in python 3.8.10, but this error show again when I executing. 

> roslaunch carla_ros_bridge carla_ros_bridge.launch

crying out loud....
