### ISSUE TITLE
Digital Twin tool crashing the engine

### ISSUE THREAD

**Issue by KPicherit** [carla-simulator/carla#6913]
Hello everyone,
I saw with great enthusiasm that CARLA 0.9.15 comes with procedural environment generation based on osm data. 
I tried to follow the tutorial but the Engine crashes during environment generation.
The XODR file is generated, as well as the tiles (that become available after the crash once engine is restarted), but nothing is present in the tiles when I run manual_control.py
Am I missing something here ?

Note: I run the Widget from editor mode, which I guess is the right way to go.

---------------

CARLA version: 0.9.15
Platform/OS: Ubuntu 22.04, 24GB Ram, 
Problem you have experienced: Crash following [digital twin tutorial](https://carla.readthedocs.io/en/latest/adv_digital_twin/)
What you expected to happen: Get a procedurally generated map based on selected OpenStreetmap area
Steps to reproduce: Follow the tutorial trying to import a [test road](https://www.openstreetmap.org/export#map=15/43.7285/3.3286) ([overpassAPI link](https://overpass-api.de/api/map?bbox=3.3192,43.7197,3.3384,43.7354))

----------------
Step 1

<img src="https://github.com/carla-simulator/carla/assets/107474213/c7c6c9d6-d73e-46d1-b83d-4874c8b16d05" alt="image" width="600" height="400">

----------------
Step 2

Tried this with several OpenStreetmap locations in different countries. Here: ([overpassAPI link](https://overpass-api.de/api/map?bbox=3.3192,43.7197,3.3384,43.7354))

<img src="https://github.com/carla-simulator/carla/assets/107474213/26701c5d-453a-4b1d-8fd4-5decdfa62eab" alt="image" width="600" height="400">
Click Generate

----------------
Crash

<img src="https://github.com/carla-simulator/carla/assets/107474213/f741f4ce-f4eb-4e1a-85ef-f526eca572a9" alt="image" width="600" height="400">

```
FileName TestMap, AssetName TestMap .
[None] PostInit
=== Critical error: ===
Unhandled Exception: SIGSEGV: invalid attempt to read memory at address 0x0000000000000000

Fatal error!

0x00007f2f2403b748 libUE4Editor-Engine.so!UMaterialInterface::AnalyzeMaterialProperty(EMaterialProperty, int&, bool&) [/data/UE_4.26_carla/Engine/Source/Runtime/Engine/Private/Materials/MaterialShared.cpp:3435]
0x00007f2e400e93fb libUE4Editor-MeshMergeUtilities.so!FMeshMergeUtilities::DetermineMaterialVertexDataUsage(TArray<bool, TSizedDefaultAllocator<32> >&, TArray<UMaterialInterface*, TSizedDefaultAllocator<32> > const&, UMaterialOptions const*) const [/data/UE_4.26_carla/Engine/Source/Developer/MeshMergeUtilities/Private/MeshMergeUtilities.cpp:519]
0x00007f2e400f5b04 libUE4Editor-MeshMergeUtilities.so!FMeshMergeUtilities::MergeComponentsToStaticMesh(TArray<UPrimitiveComponent*, TSizedDefaultAllocator<32> > const&, UWorld*, FMeshMergingSettings const&, UMaterialInterface*, UPackage*, FString const&, TArray<UObject*, TSizedDefaultAllocator<32> >&, FVector&, float, bool) const [/data/UE_4.26_carla/Engine/Source/Developer/MeshMergeUtilities/Private/MeshMergeUtilities.cpp:2079]
0x00007f2dceba5d81 libUE4Editor-EditorScriptingUtilities.so!UEditorLevelLibrary::MergeStaticMeshActors(TArray<AStaticMeshActor*, TSizedDefaultAllocator<32> > const&, FEditorScriptingMergeStaticMeshActorsOptions const&, AStaticMeshActor*&) [/data/UE_4.26_carla/Engine/Plugins/Editor/EditorScriptingUtilities/Source/EditorScriptingUtilities/Private/EditorLevelLibrary.cpp:1338]
```

------------- 

Here is the [full crash report](https://github.com/carla-simulator/carla/files/13364547/crashinfo-CarlaUE4-pid-53445-37F3D5068F85497DA3557AC2CBCB7713.zip)

Other information (documentation you consulted, workarounds you tried):
* Unreal and Carla fresh build
* Tried both `Using a URL` and `Downloading an OSM file and navigating in the interface` from tutorial
* Seems there is some problems with Walker animations not found as well, I don't know if this is related somehow. I updated my content folder and am now at 20231108_c5101a5 which corresponds to version defined in `Util/ContentVersions.txt`
*  Tried filtering the osm file to only keep the roads using `osmfilter`
* Tried to generate really small zones

Thanks for your help !

**Comment by domajstorovic** [comment]
I can also confirm the same issue.

My setup is pretty much the same:

- Ubuntu 22.04 (64G RAM, RTX4090)
- 0.9.15 built from source, running in editor mode

**Comment by omerfarukadastec** [comment]
I can also confirm too.

My setup is nearly same too.

- Ubuntu 20.04 (128GB RAM, RTX3090)
- 0.9.15 CARLA fresh build, running in editor mode

**Comment by xX-Conan-Xx** [comment]
The same thing happened to me.

I was running CARLA UE4 Editor inside a docker container from this [tutorial](https://carla.readthedocs.io/en/0.9.15/build_docker_unreal/)
![Screenshot from 2023-11-27 13-06-13](https://github.com/carla-simulator/carla/assets/61041807/6780b063-d803-4d8a-bf87-323dcfb9d04a)
When I press generate map, after 30 secs. This crash info pops up.
![Screenshot from 2023-11-27 13-07-22](https://github.com/carla-simulator/carla/assets/61041807/ed75746e-0a62-439d-8d58-84cc9ace4e32)

```
LoginId:-000003e8
EpicAccountId:

Caught signal 11 Segmentation fault

libUE4Editor-Engine.so!UMaterialInterface::AnalyzeMaterialProperty(EMaterialProperty, int&, bool&) [/home/carla/UE4.26/Engine/Source/Runtime/Engine/Private/Materials/MaterialShared.cpp:3435]
libUE4Editor-MeshMergeUtilities.so!FMeshMergeUtilities::DetermineMaterialVertexDataUsage(TArray<bool, TSizedDefaultAllocator<32> >&, TArray<UMaterialInterface*, TSizedDefaultAllocator<32> > const&, UMaterialOptions const*) const [/home/carla/UE4.26/Engine/Source/Developer/MeshMergeUtilities/Private/MeshMergeUtilities.cpp:519]
libUE4Editor-MeshMergeUtilities.so!FMeshMergeUtilities::MergeComponentsToStaticMesh(TArray<UPrimitiveComponent*, TSizedDefaultAllocator<32> > const&, UWorld*, FMeshMergingSettings const&, UMaterialInterface*, UPackage*, FString const&, TArray<UObject*, TSizedDefaultAllocator<32> >&, FVector&, float, bool) const [/home/carla/UE4.26/Engine/Source/Developer/MeshMergeUtilities/Private/MeshMergeUtilities.cpp:2079]
libUE4Editor-EditorScriptingUtilities.so!UEditorLevelLibrary::MergeStaticMeshActors(TArray<AStaticMeshActor*, TSizedDefaultAllocator<32> > const&, FEditorScriptingMergeStaticMeshActorsOptions const&, AStaticMeshActor*&) [/home/carla/UE4.26/Engine/Plugins/Editor/EditorScriptingUtilities/Source/EditorScriptingUtilities/Private/EditorLevelLibrary.cpp:1338]
libUE4Editor-EditorScriptingUtilities.so!UEditorLevelLibrary::execMergeStaticMeshActors(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Plugins/Editor/EditorScriptingUtilities/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/EditorScriptingUtilities/EditorLevelLibrary.gen.cpp:419]
libUE4Editor-CoreUObject.so!UObject::execCallMathFunction(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:930]
libUE4Editor-CoreUObject.so!UObject::execLetBool(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:2771]
libUE4Editor-CoreUObject.so!ProcessLocalScriptFunction(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1094]
libUE4Editor-CoreUObject.so!void ProcessScriptFunction<void (*)(UObject*, FFrame&, void*)>(UObject*, UFunction*, FFrame&, void*, void (*)(UObject*, FFrame&, void*)) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:895]
libUE4Editor-CoreUObject.so!ProcessLocalFunction(UObject*, UFunction*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1128]
libUE4Editor-CoreUObject.so!UObject::ProcessContextOpcode(FFrame&, void*, bool) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:2867]
libUE4Editor-CoreUObject.so!ProcessLocalScriptFunction(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1094]
libUE4Editor-CoreUObject.so!void ProcessScriptFunction<void (*)(UObject*, FFrame&, void*)>(UObject*, UFunction*, FFrame&, void*, void (*)(UObject*, FFrame&, void*)) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:895]
libUE4Editor-CoreUObject.so!ProcessLocalFunction(UObject*, UFunction*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1128]
libUE4Editor-CoreUObject.so!ProcessLocalScriptFunction(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1094]
libUE4Editor-CoreUObject.so!void ProcessScriptFunction<void (*)(UObject*, FFrame&, void*)>(UObject*, UFunction*, FFrame&, void*, void (*)(UObject*, FFrame&, void*)) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:895]
libUE4Editor-CoreUObject.so!ProcessLocalFunction(UObject*, UFunction*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1128]
libUE4Editor-CoreUObject.so!ProcessLocalScriptFunction(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1094]
libUE4Editor-CoreUObject.so!UFunction::Invoke(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/Class.cpp:5588]
libUE4Editor-CoreUObject.so!UObject::ProcessEvent(UFunction*, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1990]
libUE4Editor-CarlaTools.so!UOpenDriveToMap::GenerationFinished(FVector, FVector) [/home/carla/carla/Unreal/CarlaUE4/Plugins/CarlaTools/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/CarlaTools/OpenDriveToMap.gen.cpp:204]
libUE4Editor-CarlaTools.so!UOpenDriveToMap::GenerateTile() [/home/carla/carla/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp:336]
libUE4Editor-CarlaTools.so!UGenerateTileCommandlet::Main(FString const&) [/home/carla/carla/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/Commandlet/GenerateTileCommandlet.cpp:80]
UE4Editor!FEngineLoop::PreInitPostStartupScreen(char16_t const*) [/home/carla/UE4.26/Engine/Source/Runtime/Launch/Private/LaunchEngineLoop.cpp:3369]
UE4Editor!GuardedMain(char16_t const*) [/home/carla/UE4.26/Engine/Source/Runtime/Launch/Private/Launch.cpp:127]
libUE4Editor-UnixCommonStartup.so!CommonUnixMain(int, char**, int (*)(char16_t const*), void (*)()) [/home/carla/UE4.26/Engine/Source/Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:264]
libc.so.6!__libc_start_main(+0xe6)
UE4Editor!_start()

```

The crash report is here:
[crashinfo-CarlaUE4-pid-113806-374A2134C12E4F70B64564F6386848F7.zip](https://github.com/carla-simulator/carla/files/13469890/crashinfo-CarlaUE4-pid-113806-374A2134C12E4F70B64564F6386848F7.zip)

But after I clicked on close without sending the UE4 kept on running 
And after 30 secs, it crashed again.
![Screenshot from 2023-11-27 13-10-36](https://github.com/carla-simulator/carla/assets/61041807/04eb0f72-eaf6-433f-916f-1b64b47b6567)
```
LoginId:-000003e8
EpicAccountId:

Caught signal 11 Segmentation fault

libUE4Editor-Engine.so!UMaterialInterface::AnalyzeMaterialProperty(EMaterialProperty, int&, bool&) [/home/carla/UE4.26/Engine/Source/Runtime/Engine/Private/Materials/MaterialShared.cpp:3435]
libUE4Editor-MeshMergeUtilities.so!FMeshMergeUtilities::DetermineMaterialVertexDataUsage(TArray<bool, TSizedDefaultAllocator<32> >&, TArray<UMaterialInterface*, TSizedDefaultAllocator<32> > const&, UMaterialOptions const*) const [/home/carla/UE4.26/Engine/Source/Developer/MeshMergeUtilities/Private/MeshMergeUtilities.cpp:519]
libUE4Editor-MeshMergeUtilities.so!FMeshMergeUtilities::MergeComponentsToStaticMesh(TArray<UPrimitiveComponent*, TSizedDefaultAllocator<32> > const&, UWorld*, FMeshMergingSettings const&, UMaterialInterface*, UPackage*, FString const&, TArray<UObject*, TSizedDefaultAllocator<32> >&, FVector&, float, bool) const [/home/carla/UE4.26/Engine/Source/Developer/MeshMergeUtilities/Private/MeshMergeUtilities.cpp:2079]
libUE4Editor-EditorScriptingUtilities.so!UEditorLevelLibrary::MergeStaticMeshActors(TArray<AStaticMeshActor*, TSizedDefaultAllocator<32> > const&, FEditorScriptingMergeStaticMeshActorsOptions const&, AStaticMeshActor*&) [/home/carla/UE4.26/Engine/Plugins/Editor/EditorScriptingUtilities/Source/EditorScriptingUtilities/Private/EditorLevelLibrary.cpp:1338]
libUE4Editor-EditorScriptingUtilities.so!UEditorLevelLibrary::execMergeStaticMeshActors(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Plugins/Editor/EditorScriptingUtilities/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/EditorScriptingUtilities/EditorLevelLibrary.gen.cpp:419]
libUE4Editor-CoreUObject.so!UObject::execCallMathFunction(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:930]
libUE4Editor-CoreUObject.so!UObject::execLetBool(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:2771]
libUE4Editor-CoreUObject.so!ProcessLocalScriptFunction(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1094]
libUE4Editor-CoreUObject.so!void ProcessScriptFunction<void (*)(UObject*, FFrame&, void*)>(UObject*, UFunction*, FFrame&, void*, void (*)(UObject*, FFrame&, void*)) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:895]
libUE4Editor-CoreUObject.so!ProcessLocalFunction(UObject*, UFunction*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1128]
libUE4Editor-CoreUObject.so!UObject::ProcessContextOpcode(FFrame&, void*, bool) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:2867]
libUE4Editor-CoreUObject.so!ProcessLocalScriptFunction(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1094]
libUE4Editor-CoreUObject.so!void ProcessScriptFunction<void (*)(UObject*, FFrame&, void*)>(UObject*, UFunction*, FFrame&, void*, void (*)(UObject*, FFrame&, void*)) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:895]
libUE4Editor-CoreUObject.so!ProcessLocalFunction(UObject*, UFunction*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1128]
libUE4Editor-CoreUObject.so!ProcessLocalScriptFunction(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1094]
libUE4Editor-CoreUObject.so!void ProcessScriptFunction<void (*)(UObject*, FFrame&, void*)>(UObject*, UFunction*, FFrame&, void*, void (*)(UObject*, FFrame&, void*)) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:895]
libUE4Editor-CoreUObject.so!ProcessLocalFunction(UObject*, UFunction*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1128]
libUE4Editor-CoreUObject.so!ProcessLocalScriptFunction(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1094]
libUE4Editor-CoreUObject.so!UFunction::Invoke(UObject*, FFrame&, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/Class.cpp:5588]
libUE4Editor-CoreUObject.so!UObject::ProcessEvent(UFunction*, void*) [/home/carla/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1990]
libUE4Editor-CarlaTools.so!UOpenDriveToMap::GenerationFinished(FVector, FVector) [/home/carla/carla/Unreal/CarlaUE4/Plugins/CarlaTools/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/CarlaTools/OpenDriveToMap.gen.cpp:204]
libUE4Editor-CarlaTools.so!UOpenDriveToMap::GenerateTile() [/home/carla/carla/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp:336]
libUE4Editor-CarlaTools.so!UGenerateTileCommandlet::Main(FString const&) [/home/carla/carla/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/Commandlet/GenerateTileCommandlet.cpp:80]
UE4Editor!FEngineLoop::PreInitPostStartupScreen(char16_t const*) [/home/carla/UE4.26/Engine/Source/Runtime/Launch/Private/LaunchEngineLoop.cpp:3369]
UE4Editor!GuardedMain(char16_t const*) [/home/carla/UE4.26/Engine/Source/Runtime/Launch/Private/Launch.cpp:127]
libUE4Editor-UnixCommonStartup.so!CommonUnixMain(int, char**, int (*)(char16_t const*), void (*)()) [/home/carla/UE4.26/Engine/Source/Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:264]
libc.so.6!__libc_start_main(+0xe6)
UE4Editor!_start()
```

The report is here: 
[crashinfo-CarlaUE4-pid-116438-37CF62CD740144ABAEC8ACAD707B9F1D.zip](https://github.com/carla-simulator/carla/files/13469921/crashinfo-CarlaUE4-pid-116438-37CF62CD740144ABAEC8ACAD707B9F1D.zip)
When I pressed close and sending again the UE4 editor kept on running again and I found a StreetMapActor in the world outlier
![Screenshot from 2023-11-27 13-13-41](https://github.com/carla-simulator/carla/assets/61041807/e5171398-0640-4ac4-b59d-a9856883b8a4)
And after I click on BuildMesh inside the details of that actor a white mesh of the buildings appear
![Screenshot from 2023-11-27 13-16-27](https://github.com/carla-simulator/carla/assets/61041807/1f3b15b0-6754-4971-bab4-e842ac8441db)
Which is actually correct, but the road infomation is not shown and the buildings are not textured as well.

I am a bit lost here. Seems like some function worked but others didn't.
Here is the full output from my terminal:
[TerminalLog1.txt](https://github.com/carla-simulator/carla/files/13469987/TerminalLog1.txt)

**Comment by j-cyoung** [comment]
+1

**Comment by gitkatrin** [comment]
Same problem for me, if there are houses on the map. It builds the "Open Drive" but not the "Static" folder inside the map folder and you cannot see anything. The tip from  @xX-Conan-Xx with "BildMesh" works also for me but still no streets and trees and and...

Somehow it works with maps without houses on. Streets and trees are no problem. As you can see here is also the "Static" folder.
![Screenshot from 2023-12-12 14-18-20](https://github.com/carla-simulator/carla/assets/43642275/7bd23225-8c77-483a-9051-889f2cd77af9)

**Comment by zjr-bit** [comment]
I meet the same situation as @gitkatrin : when the map includes buildings, it will crash.

**Comment by scretvaule** [comment]
Why is there no plugin file after I compile
![image](https://github.com/carla-simulator/carla/assets/91879194/6e8dfdae-4750-4fb5-ba2c-225e8cd21c43)

**Comment by matejm42** [comment]
> Why is there no plugin file after I compile ![image](https://private-user-images.githubusercontent.com/91879194/293176094-6e8dfdae-4750-4fb5-ba2c-225e8cd21c43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDc1MjcsIm5iZiI6MTcwNDcwNzIyNywicGF0aCI6Ii85MTg3OTE5NC8yOTMxNzYwOTQtNmU4ZGZkYWUtNDc1MC00ZmI1LWJhMmMtMjI1ZThjZDIxYzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5NDcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNGMxYzNiMTY4YjFhMGZiNjA3MTdhYjkwNGYzNjMyNzFhNzk5YzljYjFjZDZhZTFhOGYxYjc1ZTllZjA5ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sA1NObtint3wTdrT1pBanst3QhPsEYy8F4Lz9GGiPak)
@scretvaule try #7053 I might have the same problem

And to others, thank you for your tips. I was able to duplicate your steps. With buildings, it always crashes, but I can generate nice mash, if I let the simulator running, but no streets. The tool works, if there are no buildings, although the generated map is not really similar to the original:
Generated map:
![Screenshot from 2024-01-08 12-51-57 the whole map](https://github.com/carla-simulator/carla/assets/116560704/7b2916ab-e445-4207-ab3c-07379a6e3042)
Original
![Screenshot from 2024-01-08 14-30-57map](https://github.com/carla-simulator/carla/assets/116560704/bfaf2777-19c0-4ae7-95a0-7318a6fe5ea9)
And it has o lot of buggy trees on the road etc.
![image](https://github.com/carla-simulator/carla/assets/116560704/30750db3-d6ab-4a28-b46b-817458f86ffd)
![image](https://github.com/carla-simulator/carla/assets/116560704/8ae2b5ac-b347-401c-b0c6-3bf9c145cf44)

**Comment by Sivagopinathreddy-Vinta** [comment]
I can also confirm too.

My setup is nearly same too.

    Ubuntu 18.04 (32GB RAM, RTX4070)
    0.9.15 CARLA fresh build, running in editor mode


> Hello everyone, I saw with great enthusiasm that CARLA 0.9.15 comes with procedural environment generation based on osm data. I tried to follow the tutorial but the Engine crashes during environment generation. The XODR file is generated, as well as the tiles (that become available after the crash once engine is restarted), but nothing is present in the tiles when I run manual_control.py Am I missing something here ?
> 
> Note: I run the Widget from editor mode, which I guess is the right way to go.
> 
> CARLA version: 0.9.15 Platform/OS: Ubuntu 22.04, 24GB Ram, Problem you have experienced: Crash following [digital twin tutorial](https://carla.readthedocs.io/en/latest/adv_digital_twin/) What you expected to happen: Get a procedurally generated map based on selected OpenStreetmap area Steps to reproduce: Follow the tutorial trying to import a [test road](https://www.openstreetmap.org/export#map=15/43.7285/3.3286) ([overpassAPI link](https://overpass-api.de/api/map?bbox=3.3192,43.7197,3.3384,43.7354))
> 
> Step 1
> <img alt="image" width="600" height="400" src="https://private-user-images.githubusercontent.com/107474213/283095766-c7c6c9d6-d73e-46d1-b83d-4874c8b16d05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0Mzk4MzMsIm5iZiI6MTcwNjQzOTUzMywicGF0aCI6Ii8xMDc0NzQyMTMvMjgzMDk1NzY2LWM3YzZjOWQ2LWQ3M2UtNDZkMS1iODNkLTQ4NzRjOGIxNmQwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxMDU4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzJhZWZhZGY4NDk3YmNkMTMwN2MzZTk0MTY1MThlMGI5NGI2YTJhYWQzYTUwZjU4NzZiZTY0NWY0MzhmZmIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D_FdHQxp2ZjeQGdwLX7MKQtLK1wUufK-1ueB-kU6c6Y">
> 
> Step 2
> 
> Tried this with several OpenStreetmap locations in different countries. Here: ([overpassAPI link](https://overpass-api.de/api/map?bbox=3.3192,43.7197,3.3384,43.7354))
> <img alt="image" width="600" height="400" src="https://private-user-images.githubusercontent.com/107474213/283111529-26701c5d-453a-4b1d-8fd4-5decdfa62eab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0Mzk4MzMsIm5iZiI6MTcwNjQzOTUzMywicGF0aCI6Ii8xMDc0NzQyMTMvMjgzMTExNTI5LTI2NzAxYzVkLTQ1M2EtNGIxZC04ZmQ0LTVkZWNkZmE2MmVhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxMDU4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjQ5Mzk0ZTUyNzczMTlmY2Q0MmRlZDFlNWM0Mzk5MTRhOWIzNGYyNDJhZWE3ZWQxYjMyOTMxMzkyZWIzY2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kfmxny9lCuZug34Y5OrXokTV1FBbXDE2fYLQ-wyReDw"> Click Generate
> 
> Crash
> <img alt="image" width="600" height="400" src="https://private-user-images.githubusercontent.com/107474213/283112144-f741f4ce-f4eb-4e1a-85ef-f526eca572a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0Mzk4MzMsIm5iZiI6MTcwNjQzOTUzMywicGF0aCI6Ii8xMDc0NzQyMTMvMjgzMTEyMTQ0LWY3NDFmNGNlLWY0ZWItNGUxYS04NWVmLWY1MjZlY2E1NzJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxMDU4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGQwN2IxYzhhZjhkOGRjODBiMDU5MTBhNWM5YjgzZmFiNTMwZGQ3Mjg3ZDhkNGQxNTUwNzk0N2I2NzM0ZWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3Oi3jt-GGAUCpvPdJGXjjbIw4t1RJwemx-nEbDIMmds">
> 
> ```
> FileName TestMap, AssetName TestMap .
> [None] PostInit
> === Critical error: ===
> Unhandled Exception: SIGSEGV: invalid attempt to read memory at address 0x0000000000000000
> 
> Fatal error!
> 
> 0x00007f2f2403b748 libUE4Editor-Engine.so!UMaterialInterface::AnalyzeMaterialProperty(EMaterialProperty, int&, bool&) [/data/UE_4.26_carla/Engine/Source/Runtime/Engine/Private/Materials/MaterialShared.cpp:3435]
> 0x00007f2e400e93fb libUE4Editor-MeshMergeUtilities.so!FMeshMergeUtilities::DetermineMaterialVertexDataUsage(TArray<bool, TSizedDefaultAllocator<32> >&, TArray<UMaterialInterface*, TSizedDefaultAllocator<32> > const&, UMaterialOptions const*) const [/data/UE_4.26_carla/Engine/Source/Developer/MeshMergeUtilities/Private/MeshMergeUtilities.cpp:519]
> 0x00007f2e400f5b04 libUE4Editor-MeshMergeUtilities.so!FMeshMergeUtilities::MergeComponentsToStaticMesh(TArray<UPrimitiveComponent*, TSizedDefaultAllocator<32> > const&, UWorld*, FMeshMergingSettings const&, UMaterialInterface*, UPackage*, FString const&, TArray<UObject*, TSizedDefaultAllocator<32> >&, FVector&, float, bool) const [/data/UE_4.26_carla/Engine/Source/Developer/MeshMergeUtilities/Private/MeshMergeUtilities.cpp:2079]
> 0x00007f2dceba5d81 libUE4Editor-EditorScriptingUtilities.so!UEditorLevelLibrary::MergeStaticMeshActors(TArray<AStaticMeshActor*, TSizedDefaultAllocator<32> > const&, FEditorScriptingMergeStaticMeshActorsOptions const&, AStaticMeshActor*&) [/data/UE_4.26_carla/Engine/Plugins/Editor/EditorScriptingUtilities/Source/EditorScriptingUtilities/Private/EditorLevelLibrary.cpp:1338]
> ```
> 
> Here is the [full crash report](https://github.com/carla-simulator/carla/files/13364547/crashinfo-CarlaUE4-pid-53445-37F3D5068F85497DA3557AC2CBCB7713.zip)
> 
> Other information (documentation you consulted, workarounds you tried):
> 
>     * Unreal and Carla fresh build
> 
>     * Tried both `Using a URL` and `Downloading an OSM file and navigating in the interface` from tutorial
> 
>     * Seems there is some problems with Walker animations not found as well, I don't know if this is related somehow. I updated my content folder and am now at 20231108_c5101a5 which corresponds to version defined in `Util/ContentVersions.txt`
> 
>     * Tried filtering the osm file to only keep the roads using `osmfilter`
> 
>     * Tried to generate really small zones
> 
> 
> Thanks for your help !

I can also confirm too.

My setup is nearly same too.

    Ubuntu 18.04 (32GB RAM, RTX4070)
    0.9.15 CARLA fresh build, running in editor mode

**Comment by andiven** [comment]
I can also confirm too.

```
Ubuntu 22.04.3  (24GB, RTX 3090)
0.9.15  and master (2024.1.20)
```

**Comment by myersryan** [comment]
Same issue,

```
Ubuntu 20.04  (64GB, RTX 4090)
0.9.15  and master
```

**Comment by donghaiwang** [comment]
Same issue,
`Windows 10 (64G, RTX 3090) 
test in 0.9.15 and dev branch`

**Comment by Blyron** [comment]
Material crash is fixed in dev branch. For windows we are not gonna be able to generate largemaps yet.

**Comment by donghaiwang** [comment]
> Material crash is fixed in dev branch. For windows we are not gonna be able to generate largemaps yet.

Thank you for fixing this issue, but do you have any plans or ideas for fixing the issues that only the first tile but other map tiles have not been generated in windows.
![image](https://github.com/carla-simulator/carla/assets/7724320/149bfb47-aeea-4ee5-bcc3-88948ab4d4c3)
![image](https://github.com/carla-simulator/carla/assets/7724320/5d60c822-023d-404f-a5c2-9d18065a39e4)

**Comment by Blyron** [comment]
It should be fixed and working as expected now.
I will be closing this issue, if something comes up, please feel free to reopen

**Comment by diespondency** [comment]
I still have the same issue as described by others, the generation of the map sometimes works, sometimes it doesn't. When it works, only the buildings are generated and all the information about the roads is gone. It's not clear to me why for some osm's it works and for others everything crashes

**Comment by joeyleehk** [comment]
I have tried to go through the whole digital twin tools in Carla 0.9.15 version and I also faced many compile and link issues when built the osmrenderer and CarlaToolsContent/OnroadMapGenerator. However, I figure them out. Here is a list of corresponding solutions: 
1. make osmrenderer: This one needs dependencies and built libosmscout and lunasvg packages. The configuration file locates in ${CARLA_BUILD_FOLDER}/Util/BuildTools/BuildOSMRenderer.sh. In this .sh file, you can see the libosmscout with specific version on Github can be cloned. 

2. But for lunasvg, it will clone the lastest version from Github. 

- This one will cause the error "`error: ‘class lunasvg::Bitmap’ has no member named ‘valid`’". The reason is the lastest lunasvg has been removed this function from its source code, replacing with isNull(). To figure this issue, it is better to manually colne the [v.2.3.8](https://github.com/sammycage/lunasvg/releases/tag/v2.3.8) to the ${CARLA_BUILD_FOLDER}/lunasvg-source (create the folder by yourself). And the comment these lines in .sh file: 
> #echo "Cloning luna-svg"
> #if [ ! -d ${LUNASVG_SOURCE_FOLDER} ] ; then
> #git clone ${LUNASVG_REPO} ${LUNASVG_SOURCE_FOLDER}
> #fi

After this lunasvg can be built smoothly. 
For Authors: would you please add the specific lunasvg COMMIT code in this .sh file? This can avoid the has no member issue. 

3. When built osm-map-renderer, it is suggested to run make PythonAPI firstly. Because the boost-1.80.0-c10-install is needed for building osm-map-renderer. Also, please modify the 

```
cmake -DCMAKE_CXX_FLAGS="-std=c++17 -g -pthread -I${CARLA_BUILD_FOLDER}/boost-1.80.0-c10-install/include" \
    ${OSM_RENDERER_SOURCE}
```
to 
 ```
cmake -DCMAKE_CXX_FLAGS="-std=c++17 -g -pthread -I${CARLA_BUILD_FOLDER}/boost-1.80.0-c10-install/include" \
-DCMAKE_EXE_LINKER_FLAGS="-L${CARLA_BUILD_FOLDER}/boost-1.80.0-c10-install/lib -lboost_system"\
    ${OSM_RENDERER_SOURCE}
```
to link the .a .so file correspondingly. 
4. The issue "usr/include/boost/system/error_code.hpp:206: undefined reference to boost::system::generic_category()'" could be raised during osmrenderer buit. Please add this command in ${OSM_RENDERER_SOURCE}/CMakeLists.txt: add_definitions(-DBOOST_ERROR_CODE_HEADER_ONLY).
5. When osmrenderer is correctly built, do make PythonAPI. 
6. After launch CarlaUE4, you can use CarlaToolsContent/OnroadMapGenerator to generate the whole scene, including buildings. PLEASE MAKE SURE THERE NO SPECIFIC SYMBOL LIKE &|* IN YOUR DOWNLOADED OSM FILE. If these symbols exist please remove or modify them in the OSM file. 
7. After this, run ./build.sh <osm_dir> in {CARLA_ROOT}/Build/libosmcout-source/maps/ to cook the osm file. Then, open UW_OnRoadMainWidget in Unreal and copy the file dir into Select OSM Database, and Please DO NOT CLICK any Button, otherwise the Unreal will crash. 
8. Open a new cmd under {CARLA_ROOT}/Build/osm-world-renderer-build and run ./osm-world-renderer. Until you see "Starting renderer C
┌ Waiting Command.."
9. Click Config and Render in UW_OnRoadMainWidget, also you need to input the geoloaction in Navigation Settings, which can be checked in OSM webpage. Then, you can see the osm map rendered.
10. IMPORTANT: after all setting, please input you File Name, and input you downloaded and modified local .osm file in XODR OR OSM FilePath. Then, click the Generate and have a cup of coffee. 
11. Enjoy the scene you created. Here is my example: 
![Screenshot from 2024-09-27 15-38-12](https://github.com/user-attachments/assets/a3bff296-5c85-466a-bb19-b315520b94f3)


```

**Comment by rohanNkhaire** [comment]
@joeyleehk Hey, I followed your instructions. However, I am getting invalid character error in the building name. I modified the downloaded .osm file - the original name tag had v="xxxx &amp; xxxx", I modified it to just v="Building". Then built the. Osm using libosmscout. Then I tried to generate the map and I still get the error invalid character xxxx_&amp;_xxxx

**Comment by joeyleehk** [comment]
Hi Rohan, have you tried to input the dir of your modified .osm file in the XDOR OR OSM FilePath and define the Geo Coords Orgin. otherwise, it will download the .osm from the OpenStreetMap website.

**Comment by zihaosheng** [comment]
Hi @joeyleehk , thanks for your sharing! I followed your steps and succeeded in the first 9 steps. But I failed in Step 10. 
I don't quite understand what you mean by `input you downloaded and modified local .osm file in XODR OR OSM FilePath`, and I didn’t see where I can input the XODR OR OSM FilePath. 
Could you please provide more details on how this is done? Thank you so much!

**Comment by IrfanAli91170** [comment]
Excuse me, i just install the Digital Twins rool and all built well. 
But, following the instructions to render OSM maps in CARLA, the rendered map does not appear in the UW_OnRoadMainWidget after Step 9 (Config and Render). 
No errors are displayed, but the widget remains blank. 

These are the steps that I followed :

I first compiled 'make osmrenderer' without any issues. Then, I cooked the OSM file, which I extracted from the OpenStreetMap website for a small area, using ./build.sh, and it worked fine.

Next, I launched CARLA with 'make launch', then opened the UW_OnRoadMainWidget widget. I correctly specified the path to the cooked OSM folder (without clicking any buttons).

In a second terminal, I ran ./osm-world-renderer, and I could see the message:

Starting renderer C
┌ Waiting Command..


Finally, I clicked on 'Config' and 'Render' in the widget, but nothing happened.

I urgently need help with this issue for my work. Could you please assist me?

**Comment by IrfanAli91170** [comment]
That's the message when the UE4 crashed :

![Image](https://github.com/user-attachments/assets/640585e4-bbcd-4bad-a1f6-dc286e252f0c)

[CarlaUE4.log](https://github.com/user-attachments/files/18884091/CarlaUE4.log)

LoginId:7336a0be5b4d913d4c77d8506790bfe7-000003e8
EpicAccountId:

Assertion failed: (Index >= 0) & (Index < ArrayNum) [File:Runtime/Core/Public/Containers/Array.h] [Line: 674] Array index out of bounds: 1 from an array of size 1

libUE4Editor-Core.so!FGenericPlatformMisc::RaiseException(unsigned int) [/home/scarlet/UE4.26/Engine/Source/Runtime/Core/Private/GenericPlatform/GenericPlatformMisc.cpp:472]
libUE4Editor-Core.so!FOutputDevice::LogfImpl(char16_t const*, ...) [/home/scarlet/UE4.26/Engine/Source/Runtime/Core/Private/Misc/OutputDevice.cpp:61]
libUE4Editor-Core.so!AssertFailedImplV(char const*, char const*, int, char16_t const*, __va_list_tag*) [/home/scarlet/UE4.26/Engine/Source/Runtime/Core/Private/Misc/AssertionMacros.cpp:104]
libUE4Editor-Core.so!FDebug::CheckVerifyFailedImpl(char const*, char const*, int, char16_t const*, ...) [/home/scarlet/UE4.26/Engine/Source/Runtime/Core/Private/Misc/AssertionMacros.cpp:458]
libUE4Editor-CarlaTools.so!UMapPreviewUserWidget::UpdateLatLonCoordProperties() [/home/scarlet/carla/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/MapPreviewUserWidget.cpp:205]
libUE4Editor-CoreUObject.so!UFunction::Invoke(UObject*, FFrame&, void*) [/home/scarlet/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/Class.cpp:5588]
libUE4Editor-CoreUObject.so!UObject::CallFunction(FFrame&, void*, UFunction*) [/home/scarlet/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:997]
libUE4Editor-CoreUObject.so!UObject::ProcessContextOpcode(FFrame&, void*, bool) [/home/scarlet/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:2867]
libUE4Editor-CoreUObject.so!ProcessLocalScriptFunction(UObject*, FFrame&, void*) [/home/scarlet/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1094]
libUE4Editor-CoreUObject.so!void ProcessScriptFunction<void (*)(UObject*, FFrame&, void*)>(UObject*, UFunction*, FFrame&, void*, void (*)(UObject*, FFrame&, void*)) [/home/scarlet/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:895]
libUE4Editor-CoreUObject.so!ProcessLocalFunction(UObject*, UFunction*, FFrame&, void*) [/home/scarlet/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1128]
libUE4Editor-CoreUObject.so!ProcessLocalScriptFunction(UObject*, FFrame&, void*) [/home/scarlet/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1094]
libUE4Editor-CoreUObject.so!void ProcessScriptFunction<void (*)(UObject*, FFrame&, void*)>(UObject*, UFunction*, FFrame&, void*, void (*)(UObject*, FFrame&, void*)) [/home/scarlet/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:895]
libUE4Editor-CoreUObject.so!ProcessLocalFunction(UObject*, UFunction*, FFrame&, void*) [/home/scarlet/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1128]
libUE4Editor-CoreUObject.so!ProcessLocalScriptFunction(UObject*, FFrame&, void*) [/home/scarlet/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1094]
libUE4Editor-CoreUObject.so!UFunction::Invoke(UObject*, FFrame&, void*) [/home/scarlet/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/Class.cpp:5588]
libUE4Editor-CoreUObject.so!UObject::ProcessEvent(UFunction*, void*) [/home/scarlet/UE4.26/Engine/Source/Runtime/CoreUObject/Private/UObject/ScriptCore.cpp:1990]
libUE4Editor-UMG.so!void TScriptDelegate<FWeakObjectPtr>::ProcessDelegate<UObject>(void*) const [/home/scarlet/UE4.26/Engine/Source/Runtime/Core/Public/UObject/ScriptDelegates.h:247]
libUE4Editor-UMG.so!void TMulticastScriptDelegate<FWeakObjectPtr>::ProcessMulticastDelegate<UObject>(void*) const [/home/scarlet/UE4.26/Engine/Source/Runtime/Core/Public/UObject/ScriptDelegates.h:493]
libUE4Editor-UMG.so!UButton::SlateHandleClicked() [/home/scarlet/UE4.26/Engine/Source/Runtime/UMG/Private/Components/Button.cpp:203]
libUE4Editor-UMG.so!TBaseUObjectMethodDelegateInstance<false, UButton, FReply (), FDefaultDelegateUserPolicy>::Execute() const [/home/scarlet/UE4.26/Engine/Source/Runtime/Core/Public/Delegates/DelegateInstancesImpl.h:593]
libUE4Editor-Slate.so!SButton::ExecuteOnClick() [/home/scarlet/UE4.26/Engine/Source/Runtime/Slate/Private/Widgets/Input/SButton.cpp:385]
libUE4Editor-Slate.so!SButton::OnMouseButtonUp(FGeometry const&, FPointerEvent const&) [/home/scarlet/UE4.26/Engine/Source/Runtime/Slate/Private/Widgets/Input/SButton.cpp:304]
libUE4Editor-Slate.so!FSlateApplication::RoutePointerUpEvent(FWidgetPath const&, FPointerEvent const&) [/home/scarlet/UE4.26/Engine/Source/Runtime/Slate/Private/Framework/Application/SlateApplication.cpp:4823]
libUE4Editor-Slate.so!FSlateApplication::ProcessMouseButtonUpEvent(FPointerEvent const&) [/home/scarlet/UE4.26/Engine/Source/Runtime/Slate/Private/Framework/Application/SlateApplication.cpp:5363]
libUE4Editor-Slate.so!FSlateApplication::OnMouseUp(EMouseButtons::Type, FVector2D) [/home/scarlet/UE4.26/Engine/Source/Runtime/Slate/Private/Framework/Application/SlateApplication.cpp:5328]
libUE4Editor-ApplicationCore.so!FLinuxApplication::ProcessDeferredMessage(SDL_Event) [/home/scarlet/UE4.26/Engine/Source/Runtime/ApplicationCore/Private/Linux/LinuxApplication.cpp:370]
libUE4Editor-ApplicationCore.so!FLinuxPlatformApplicationMisc::PumpMessages(bool) [/home/scarlet/UE4.26/Engine/Source/Runtime/ApplicationCore/Private/Linux/LinuxPlatformApplicationMisc.cpp:428]
UE4Editor!FEngineLoop::Tick() [/home/scarlet/UE4.26/Engine/Source/Runtime/Launch/Private/LaunchEngineLoop.cpp:4748]
UE4Editor!GuardedMain(char16_t const*) [/home/scarlet/UE4.26/Engine/Source/Runtime/Launch/Private/Launch.cpp:171]
libUE4Editor-UnixCommonStartup.so!CommonUnixMain(int, char**, int (*)(char16_t const*), void (*)()) [/home/scarlet/UE4.26/Engine/Source/Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:264]
libc.so.6!__libc_start_main(+0xe6)

**Comment by ponljung** [comment]
I tried to follow above steps from @joeyleehk but seem to still have similar issues as the @KPicherit had in the beginning. I did also go over the OSM file to check for mentioned characters but the issue is still present, i.e it crashes during generation. 

Steps: 

![Image](https://github.com/user-attachments/assets/c988d239-a27a-44e4-84e6-6b978a2ded63)

Selecting the area: 

![Image](https://github.com/user-attachments/assets/d523ccee-6cde-43ec-963f-77478d99e49c)

I see during generation that this error log is created: 

**[2025.04.13-15.40.26:152][165]LogCarlaTools: Error: Creating New Object**

The generation is then terminated and a log dump from UE is created. Closing without sending still keeps the generation going in the background.

![Image](https://github.com/user-attachments/assets/576fe376-5457-467c-9bde-8d5e07076e8f)

Running Carla version 0.9.15.2

Full log can be found below:
[log.txt](https://github.com/user-attachments/files/19726083/log.txt)
