### ISSUE TITLE
Segmentation fault: Signal 11 caught. Malloc Size=65538 LargeMemoryPoolOffset=65554

### ISSUE THREAD

**Issue by Rak-r** [carla-simulator/carla#9152]
**Setup**
Describe the setup you are using to run CARLA along with its version:
  * CARLA version: 0.9.15 (not source build)
  * Platform: Ubuntu 22.04 LTS
  * Python version: 3.7
  * GPU: Nvidia 16gb RTX A5000 Ada
  

**Describe the bug**
Hello, I am bit new to Carla and I try to make simple a script which spawns an ego vehicle and two sensors (rgb and semantic) mounted on it. Similarly I attach 2 sensors (rgb and semantic cam) to the static traffic light (infra) which is already spawned when the map loads. I write separate callbacks for ego vehicle sensors and traffic light (infra) sensors and take some reference from tutorial's `manual_control.py` script for simulation loop which spawns one sensor at a time. In my script I spawn all 4 sensors and ego-vehicle and traffic light simultaneously. Now starting the carla server and running the script, it starts but when I press Ctrl+C (kill the script), after few seconds the Carla servers crashes with segmentation error as shown in logs below.

I am struggling to find why this happens, I check that I destroy the actors and sensors and clears the list at the end where i store these. But still it seems something in the background keeps running. Is there something I am missing to destroy or handle? Because this does not happen in manual_control.py script.

I tried with single sensor and ego-vehicle, it didn't crashed but the GPU memory keeps incrementing,  monitored by `watch nvidia-smi` 

**Expected behavior**
Even if I kill the script, the server should not be crashing

**Logs**

`Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=131160 LargeMemoryPoolOffset=196744 
Malloc Size=131160 LargeMemoryPoolOffset=327928 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)`

I tried adding weakref, followed this https://github.com/carla-simulator/carla/issues/5812 but still not able to figure out where it is failing. I also tried to just comment out the listen method for more simple setup still the server crashes after I press Ctrl+C on the python script (client)
@Blyron @wambitz

**Comment by Rak-r** [comment]
I tested with carla_ros2 bridge also even without any changes and there is also the server crahses in the middle of running with this in terminal log, which shows some Vulkan related error, and I think the same is happening in python side as well but what is the fix as I have searched for it but got nothing major to look for. I updated my nvidia driver as well, image below, shows the details of nvidia-smi.

`LowLevelFatalError [File:Unknown] [Line: 803] 
DeviceMemoryManager->GetMemoryTypeFromPropertiesExcluding(MemoryReqs.memoryTypeBits, MemoryPropertyFlags, TypeIndex, &TypeIndex) failed, VkResult=-8
 at /home/jenkins/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanMemory.cpp:3003 
 with error VK_ERROR_FEATURE_NOT_PRESENT
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=131160 LargeMemoryPoolOffset=196744 
Malloc Size=131160 LargeMemoryPoolOffset=327928 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)
`

<img width="813" height="381" alt="Image" src="https://github.com/user-attachments/assets/8706d0a6-1ed6-4c64-b988-f8162f2cf637" />

**Comment by Rak-r** [comment]
I have tried to just use LiDAR sensor instead of any cameras as discussed in this [https://github.com/carla-simulator/carla/issues/7156#issue-2140776207](url) but there is still some leak I think. But the server continued to run for longer duration and didn't crash. If the memory keeps allocating for longer duration, it ultimately will crash.

**The output for VRAM monitoring.**
<img width="984" height="1103" alt="Image" src="https://github.com/user-attachments/assets/49f42321-109b-4199-abdb-ec74a2a5c0b6" />

I am having no clue what to try out now to fix this and achieve consistent server running. @Blyron

**Comment by Blyron** [comment]
Please try latest nightly build for UE4 or ue4-dev branch for source. We fixed a memory leak recently

**Comment by Blyron** [comment]
Hello! Have you tried with nightly build?

**Comment by Rak-r** [comment]
> Please try latest nightly build for UE4 or ue4-dev branch for source. We fixed a memory leak recently

I already did the source build version of ue4-dev, last week for this: `git describe --tags`
`0.9.15-381-gadba3c39b`
` but still have that issue persist. Shall I again try the nightly build version?

**Comment by Blyron** [comment]
What happens if you try git status?

**Comment by Rak-r** [comment]
> **Setup** Describe the setup you are using to run CARLA along with its version:
> 
>     * CARLA version: 0.9.15 (not source build)
> 
>     * Platform: Ubuntu 22.04 LTS
> 
>     * Python version: 3.7
> 
>     * GPU: Nvidia 16gb RTX A5000 Ada
> 
> 
> **Describe the bug** Hello, I am bit new to Carla and I try to make simple a script which spawns an ego vehicle and two sensors (rgb and semantic) mounted on it. Similarly I attach 2 sensors (rgb and semantic cam) to the static traffic light (infra) which is already spawned when the map loads. I write separate callbacks for ego vehicle sensors and traffic light (infra) sensors and take some reference from tutorial's `manual_control.py` script for simulation loop which spawns one sensor at a time. In my script I spawn all 4 sensors and ego-vehicle and traffic light simultaneously. Now starting the carla server and running the script, it starts but when I press Ctrl+C (kill the script), after few seconds the Carla servers crashes with segmentation error as shown in logs below.
> 
> I am struggling to find why this happens, I check that I destroy the actors and sensors and clears the list at the end where i store these. But still it seems something in the background keeps running. Is there something I am missing to destroy or handle? Because this does not happen in manual_control.py script.
> 
> I tried with single sensor and ego-vehicle, it didn't crashed but the GPU memory keeps incrementing, monitored by `watch nvidia-smi`
> 
> **Steps to reproduce: simply run my script**
> 
> **Expected behavior** Even if I kill the script, the server should not be crashing
> 
> **Logs**
> 
> `Signal 11 caught. Malloc Size=65538 LargeMemoryPoolOffset=65554 CommonUnixCrashHandler: Signal=11 Malloc Size=131160 LargeMemoryPoolOffset=196744 Malloc Size=131160 LargeMemoryPoolOffset=327928 Engine crash handling finished; re-raising signal 11 for the default handler. Good bye. Segmentation fault (core dumped)`


**Regarding the second segmentation fault issue:**

`[2025.08.15-10.01.02:787][113]LogCarla: UActorDispatcher::Destroying actor: 'traffic.traffic_light' cb65b530 [2025.08.15-10.01.02:787][113]LogCarla: BP_TrafficLightNew_T10_master_largeBIG_rsc_2 the above came when i rerun my script after correcting the typo if vehcile name, then i could see the image data printing and then i killed the script of by ctrl+c and within few seconds this came in the same terminla log: Signal 11 caught. Malloc Size=65538 LargeMemoryPoolOffset=65554 CommonUnixCrashHandler: Signal=11 [2025.08.15-10.02.18:802][712]LogCore: === Critical error: === Unhandled Exception: SIGSEGV: invalid attempt to write memory at address 0x000000000000024
`

My python client script was spawning two sensors attached to a traffic light which was already spawned during map loaded. The script after keyboardInterrupt , destroys all actors and I kept track of the traffic light as well to which the sensors were attached and it gets destroyed at the end. This destruction of traffic light by python client is the root cause of segmentation fault because the TrafficLightGroup tried to tick to change the light states for all the spawned traffic light actors but due to the destruction of one of the actor it ends up in dangling reference.

I tested the same script with complete removal of traffic light and it ran perfectly I killed it in middle using Ctrl+C , the server kept running (no crash), I ran it again, it works!!.

**Comment by Blyron** [comment]
Have you tried to do a "make PythonAPI" when using from source installation? instead of using the one from pypi

**Comment by Rak-r** [comment]
This is what I get when I do `git status`:

**Output:** 

` 
  On branch ue4-dev
  Your branch is up to date with 'origin/ue4-dev'.
  Untracked files:
    (use "git add <file>..." to include in what will be committed)
	 Unreal/CarlaUE4/.ignore
    nothing added to commit but untracked files present (use "git add" to track)

   `

**Comment by Rak-r** [comment]
> Have you tried to do a "make PythonAPI" when using from source installation? instead of using the one from pypi

Yes I followed the instructions from the documentation here: https://carla.readthedocs.io/en/latest/build_linux/

which tells to run `make PythonAPI`

**Comment by Blyron** [comment]
Okay. Then it should be working. We will test this.

**Comment by Rak-r** [comment]
> Okay. Then it should be working. We will test this.

Ok thank you. I will await your response as I am still having this issue hanging for UE4. For the moment, I have binary build for new Carla 0.10 with UE5 which do not have this issue as I tested it by running for atleast an hour with VRAM monitoring and it handles it as it should.

**Comment by Blyron** [comment]
That doesn't make sense. UE4-DEV and ue5 handles the same way the memory from server to client. Please try with latest binary build.  
https://carla.readthedocs.io/en/latest/download/#nightly-build

**Comment by Rak-r** [comment]
I tested again just running the source build carla and UE editor using `make launch` in one terminal and in another terminal the PythonAPI/examples , `manual_control.py --sync` with sync mode. I moved the vehicle for a small distance toggled between different sensors and then let it run idle, I was also monitoring VRAM which kept increasing same as previously sent screenshort and then the crash happened which seems to have the same issue. So am I missing something?

**The log from UE editor:**

```
 LoginId:80b84e2bd8194c4aa4b1526a98423fb3-000003e9
    EpicAccountId:
    Assertion failed: InSize == (~0ULL) || InSize + Offset <= Size [File:/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/               VulkanRHI/Private/VulkanMemory.cpp] [Line: 1373] Failed to Map 33554432 bytes, Offset 0, AllocSize 3686400 bytes
 
  libUE4Editor-Core.so!FGenericPlatformMisc::RaiseException(unsigned int) [/home/sg08454/UnrealEngine_4.26/Engine/Source/     Runtime/Core/Private/GenericPlatform/GenericPlatformMisc.cpp:472]
 libUE4Editor-Core.so!FOutputDevice::LogfImpl(char16_t const*, ...) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/Core/Private/Misc/OutputDevice.cpp:61]
libUE4Editor-Core.so!AssertFailedImplV(char const*, char const*, int, char16_t const*, __va_list_tag*) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/Core/Private/Misc/AssertionMacros.cpp:104]
libUE4Editor-Core.so!FDebug::CheckVerifyFailedImpl(char const*, char const*, int, char16_t const*, ...) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/Core/Private/Misc/AssertionMacros.cpp:458]
libUE4Editor-VulkanRHI.so!void FDebug::CheckVerifyFailed<char16_t [60], unsigned long, unsigned long, unsigned long>(char const*, char const*, int, char16_t const (&) [60], unsigned long, unsigned long, unsigned long) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/Core/Public/Misc/AssertionMacros.h:155]
libUE4Editor-VulkanRHI.so!VulkanRHI::FDeviceMemoryAllocation::Map(unsigned long, unsigned long)::$_96::operator()() const [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanMemory.cpp:1373]
libUE4Editor-VulkanRHI.so!VulkanRHI::FDeviceMemoryAllocation::Map(unsigned long, unsigned long) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanMemory.cpp:1373]
libUE4Editor-VulkanRHI.so!VulkanRHI::FVulkanResourceHeap::AllocateResource(VulkanRHI::FVulkanAllocation&, FVulkanEvictable*, VulkanRHI::EType, unsigned int, unsigned int, bool, bool, VulkanRHI::EVulkanAllocationMetaType, char const*, unsigned int) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanMemory.cpp:2093]
libUE4Editor-VulkanRHI.so!VulkanRHI::FMemoryManager::AllocateBufferMemory(VulkanRHI::FVulkanAllocation&, FVulkanEvictable*, VkMemoryRequirements const&, unsigned int, VulkanRHI::EVulkanAllocationMetaType, char const*, unsigned int) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanMemory.cpp:3000]
libUE4Editor-VulkanRHI.so!FVulkanSurface::FVulkanSurface(FVulkanDevice&, FVulkanEvictable*, VkImageViewType, EPixelFormat, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, ETextureCreateFlags, ERHIAccess, FRHIResourceCreateInfo const&) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanTexture.cpp:604]
libUE4Editor-VulkanRHI.so!FVulkanTextureBase::FVulkanTextureBase(FVulkanDevice&, VkImageViewType, EPixelFormat, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, ETextureCreateFlags, ERHIAccess, FRHIResourceCreateInfo const&) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanTexture.cpp:2186]
libUE4Editor-VulkanRHI.so!FVulkanTexture2D::FVulkanTexture2D(FVulkanDevice&, EPixelFormat, unsigned int, unsigned int, unsigned int, unsigned int, ETextureCreateFlags, ERHIAccess, FRHIResourceCreateInfo const&) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanTexture.cpp:2516]
libUE4Editor-VulkanRHI.so!FVulkanDynamicRHI::RHICreateTexture2D_RenderThread(FRHICommandListImmediate&, unsigned int, unsigned int, unsigned char, unsigned int, unsigned int, ETextureCreateFlags, ERHIAccess, FRHIResourceCreateInfo&) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Public/VulkanDynamicRHI.h:270]
libUE4Editor-RHI.so!FRHIGPUTextureReadback::EnqueueCopyInternal(FRHICommandList&, FRHITexture*, FResolveParams) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/RHI/Private/RHIGPUReadback.cpp:143]
libUE4Editor-RHI.so!FRHIGPUTextureReadback::EnqueueCopy(FRHICommandList&, FRHITexture*, FResolveRect) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/RHI/Private/RHIGPUReadback.cpp:122]
libUE4Editor-Carla.so!FPixelReader::WritePixelsToBuffer(UTextureRenderTarget2D const&, unsigned int, FRHICommandListImmediate&, std::__1::function<void (void*, unsigned int, unsigned int, unsigned int)>) [/home/sg08454/UnrealEngine_4.26/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/PixelReader.cpp:41]
libUE4Editor-Carla.so!auto void FPixelReader::SendPixelsInRenderThread<ASceneCaptureCamera, FColor>(ASceneCaptureCamera&, bool, std::__1::function<TArray<FColor, TSizedDefaultAllocator<32> > (void*, unsigned int)>)::'lambda'(ASceneCaptureCamera&)::operator()<FRHICommandListImmediate>(ASceneCaptureCamera&) [/home/sg08454/UnrealEngine_4.26/Engine/Source/../../carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/PixelReader.h:210]
libUE4Editor-Carla.so!TEnqueueUniqueRenderCommandType<void FPixelReader::SendPixelsInRenderThread<ASceneCaptureCamera, FColor>(ASceneCaptureCamera&, bool, std::__1::function<TArray<FColor, TSizedDefaultAllocator<32> > (void*, unsigned int)>)::FWritePixels_SendPixelsInRenderThreadName, void FPixelReader::SendPixelsInRenderThread<ASceneCaptureCamera, FColor>(ASceneCaptureCamera&, bool, std::__1::function<TArray<FColor, TSizedDefaultAllocator<32> > (void*, unsigned int)>)::'lambda'(ASceneCaptureCamera&)>::DoTask(ENamedThreads::Type, TRefCountPtr<FGraphEvent> const&) [/home/sg08454/UnrealEngine_4.26/Engine/Source/./Runtime/RenderCore/Public/RenderingThread.h:183]
libUE4Editor-Carla.so!TGraphTask<TEnqueueUniqueRenderCommandType<void FPixelReader::SendPixelsInRenderThread<ASceneCaptureCamera, FColor>(ASceneCaptureCamera&, bool, std::__1::function<TArray<FColor, TSizedDefaultAllocator<32> > (void*, unsigned int)>)::FWritePixels_SendPixelsInRenderThreadName, void FPixelReader::SendPixelsInRenderThread<ASceneCaptureCamera, FColor>(ASceneCaptureCamera&, bool, std::__1::function<TArray<FColor, TSizedDefaultAllocator<32> > (void*, unsigned int)>)::'lambda'(ASceneCaptureCamera&)> >::ExecuteTask(TArray<FBaseGraphTask*, TSizedDefaultAllocator<32> >&, ENamedThreads::Type) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/Core/Public/Async/TaskGraphInterfaces.h:886]
 libUE4Editor-Core.so!FNamedTaskThread::ProcessTasksNamedThread(int, bool) [/home/sg08454/UnrealEngine_4.26/Engine/ Source/Runtime/Core/Private/Async/TaskGraph.cpp:709]
 libUE4Editor-Core.so!FNamedTaskThread::ProcessTasksUntilQuit(int) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/ Core/Private/Async/TaskGraph.cpp:600]
 libUE4Editor-RenderCore.so!RenderingThreadMain(FEvent*) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/ RenderCore/Private/RenderingThread.cpp:372]
  libUE4Editor-RenderCore.so!FRenderingThread::Run() [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/RenderCore/ Private/RenderingThread.cpp:526]
 libUE4Editor-Core.so!FRunnableThreadPThread::Run() [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/Core/Private/ HAL/PThreadRunnableThread.cpp:25]
 libUE4Editor-Core.so!FRunnableThreadPThread::_ThreadProc(void*) [/home/sg08454/UnrealEngine_4.26/Engine/Source/Runtime/ Core/Private/HAL/PThreadRunnableThread.h:185]
 libc.so.6!UnknownFunction(0x94ac2)
 libc.so.6!UnknownFunction(0x12684f)

```

**Comment by Blyron** [comment]
Could you try with a package please?  Still we will have a look.

**Comment by Rak-r** [comment]
I just build the binary version of night build and tested the same setup (even with default async mode) as explained but unfortunately ended up with same issue:

 **Screenshort of my vulkan error with  night build binary version:**

<img width="837" height="276" alt="Image" src="https://github.com/user-attachments/assets/ee082123-15da-402a-9fca-1488681260e9" />

**Screenshort of Pygame window (just in case)**

<img width="1237" height="751" alt="Image" src="https://github.com/user-attachments/assets/e8e44401-ef47-4a43-a493-09c19cef5f1f" />

**Comment by Rak-r** [comment]
Hello, could you please advice something related to the issue? I tried the night build binary as well. @Blyron

**Comment by Blyron** [comment]
Sorry I do not have a quick answer now. We will need to debug into this. You could try to use driver version 555 of nvidia.

**Comment by Rak-r** [comment]
When I check for drivers 555 is not listed by ubuntu 22.04, I am thinking is it safe to get this one or not.

**Comment by Rak-r** [comment]
Hello, I tried to check the setup with both source build version and its packaged version and also the carla nightly build version, with downgrading the nvidia driver from 575 to 535 and 550. All of these endup in same error of memory allocation. Since 555 was not listed in the Ubuntu drivers, I didn't want to break any thing in my working setup at this stage, therefore did not tested to forcefully install the driver 555. At the moment, I am able to run UE5.5 with Carla 0.10 as it should. @Blyron

**Comment by Rak-r** [comment]
Hello, just a follow-up, were you able to check what is the issue for vulkan memory method in UE4?

**Comment by afzalxo** [comment]
Hi @Rak-r, did you manage to resolve this issue? I am facing the same issue. I am using an A100 GPU and Carla 0.9.16. I encounter the same Seg fault error as you, however, it happens if I run the server, connect to it, load world town10_hd and repeat this sequence many times (over 100). I have been trying to isolate the issue, but so far the only thing that triggers is if I run evaluation on Carla many times.

**Comment by Rak-r** [comment]
@afzalxo I tried to test almost all versions of carla but not able to solve this because it is something on the UE issue not the system's fault. Right now the new Carla 0.10.0 with UE 5 runs correctly without any crashes. You could try that instead.

**Comment by afzalxo** [comment]
Thanks for the prompt response @Rak-r 

UE5 version doesn't support changing weather/time-of-day, so it doesn't fit my needs, unfortunately. The UE4 version works fine if I don't trigger evaluation frequently. So I'll stick to it for now and hope it doesn't crash too often.

**Comment by Rak-r** [comment]
Hi @afzalxo can you tell me your PC specifications along with nvidia driver version ? And Carla version?

**Comment by ytj254** [comment]
My computer specs are:

- CPU: Intel Core i9-14900KF
- RAM: 32 GB
- GPU: NVIDIA GeForce RTX 4080
- VRAM: 16 GB
- NVIDIA driver: 580.126.09
- CUDA: 13.0

I also ran into the same issue when running CARLA for a while.

```
4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=131160 LargeMemoryPoolOffset=196744 
Malloc Size=131160 LargeMemoryPoolOffset=327928 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)
```

Hope there is a solution available for this issue.

**Comment by afzalxo** [comment]
I have two machines I tried the simulator on:

Machine 1:
1 x A100 40GB GPU
Xeon(R) Gold 6246R CPU
128 GB Mem
Nvidia Driver: 550.90.07
CUDA Version: 12.4

Machine 2:
9 x RTX 4090D 48GB GPUs
2 x Xeon Platinum 8481C
1 TB Mem
Nvidia Driver: 595.58.03
CUDA Version: 13.2

I was using 0.9.16 version of CARLA. And I was facing this segfault issue on both machine in all possible configurations (one CARLA instance on one GPU, multi instances/multi GPUs etc). I then found the following solution which seems to have worked for the most part (I found the gist of this solution on another issue in this repo, but I can't find it now). The basic idea is that you need to start a clean (sub)process for CARLA from your main script. You would initialize CARLA inside the process (i.e., not in your main process but in the subprocess). This way, once this subprocess finishes, CARLA cleanup will be more thorough:

``` python3
                ctx = multiprocessing.get_context('spawn')
                if len(eval_gpus) > 1:
                    queues = []
                    processes = []
                    for i, route_indices in enumerate(ROUTES_TO_EVAL):  
                        gpu_id = eval_gpus[i % len(eval_gpus)]
                        route_device = torch.device(f"cuda:{gpu_id}")
                        route_name = ROUTES_EVAL_NAMES.get(route_indices, f"{route_indices[0]}->{route_indices[1]}")
                        q = ctx.Queue()
                        queues.append(q)
                        proc = ctx.Process(target=evaluate_single_route_wrapper,
                                           args=(tmp_weights_path, epoch, route_device, EVAL_SCENARIOS,
                                                 route_indices, route_name, EVAL_RENDER_SIZE, FOV,
                                                 True, False, gpu_id, hard_masking, q))   # evaluate_single_route_wrapper contains the eval code (below)
                        processes.append(proc)
                    for proc in processes:
                        proc.start()
                        time.sleep(3)
                    for proc in processes:
                        proc.join()
                    total_rc, total_rl, total_cte, total_fc = 0.0, 0.0, 0.0, 0
                    route_results = {}
                    for q in queues:
                        try:
                            rc, rl, cte_sum, fc, rr = q.get(timeout=30)
                            total_rc += rc; total_rl += rl; total_cte += cte_sum; total_fc += fc
                            route_results.update(rr)
                        except Exception as e:
                            print(f"Failed to get eval result: {e}")
                            total_rl = max(total_rl, 1.0); total_fc = max(total_fc, 1)
                    completion = (total_rc / total_rl) * 100.0 if total_rl > 0 else 0.0 
                    cte = total_cte / total_fc if total_fc > 0 else 0.0 
                else:
                    result_queue = ctx.Queue()
                    p = ctx.Process(target=evaluate_in_carla_mp_wrapper,
                                    args=(tmp_weights_path, epoch, DEVICE, EVAL_SCENARIOS, ROUTES_TO_EVAL,
                                          ROUTES_EVAL_NAMES, EVAL_RENDER_SIZE, FOV, True, False,
                                          result_queue, eval_gpus[0], hard_masking))
                    p.start()
                    time.sleep(5)
                    p.join()
                    completion, cte, route_results = result_queue.get()
```

Where `evaluate_single_route_wrapper` is defined as:

``` python3
def evaluate_single_route_wrapper(model_path, epoch, device, eval_scenarios, route_indices, route_name, eval_render_size, fov, gated=False, save_to_wandb=False, gpu_rank=0, hard_masking=False, result_queue=None):
    """Evaluates a single route in an isolated subprocess. Used for parallel evaluation."""
    # Seed deterministically per route so traffic layout is reproducible across runs.
    # Route-specific seed ensures different routes still get different TM ports.
    route_seed = route_indices[0] * 1000 + route_indices[1]
    random.seed(route_seed)
    np.random.seed(route_seed)
    torch.manual_seed(route_seed)
    torch.cuda.manual_seed_all(route_seed)
    torch.backends.cudnn.deterministic = True 
    torch.backends.cudnn.benchmark = False
    client_port = find_free_port(30000 + gpu_rank * 1000)
    try: 
        carla_server = CarlaServer(gpu_rank=gpu_rank, rpc_port=client_port)
        carla_proc = carla_server.start()
        client = carla.Client('localhost', client_port)
        client.set_timeout(60.0)
        client.load_world('Town10HD_Opt')
        time.sleep(5)
        world = client.get_world()
        settings = world.get_settings()
        settings.synchronous_mode = True 
        settings.fixed_delta_seconds = 0.05 
        settings.substepping = True 
        settings.max_substep_delta_time = 0.01 
        settings.max_substeps = 10 
        world.apply_settings(settings)
        weather = carla.WeatherParameters.ClearNoon
        world.set_weather(weather)
    except Exception as e:
        print(f"[GPU {gpu_rank}] Error setting up CARLA environment: {e}")
        if 'carla_server' in locals():
            if carla_server.is_server_running(client_port):
                carla_server.stop()
        if result_queue is not None:
            result_queue.put((0.0, 1.0, 0.0, 1, {})) 
        return
         
    ckpt = torch.load(model_path, map_location=device)
     
    '''# Perform your thing here (load model, run eval on the route '''
    
    carla_server.stop()
    time.sleep(5)
```

Hope this helps. Feel free to let me know if you guys run into any issues.
